name: intrezo
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^2.30.0
  cloud_firestore: ^4.0.0
  timeago: ^3.5.0
  shared_preferences: ^2.1.1  # ← для локальных избранных
  provider: ^6.0.5
  url_launcher: ^6.1.7
  share_plus: ^11.0.0
  firebase_messaging: ^14.2.3
  carousel_slider: ^5.1.1


  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/images/logo.jpg
    - assets/images/onboarding1.png
    - assets/images/onboarding2.png
    - assets/images/onboarding3.png
    - assets/images/onboarding1.png
    - assets/images/miniintrezo.png
    - assets/images/whatsapp.png
    - assets/images/viber.png
    - assets/images/about.png
    - assets/images/telegram.png